# Generated by Django 5.1.4 on 2025-01-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='final_date',
            field=models.DateField(default='2025-01-01', verbose_name='Final date'),
        ),
        migrations.AlterField(
            model_name='info',
            name='init_date',
            field=models.DateField(verbose_name='Init date'),
        ),
    ]
