# Generated by Django 5.1.4 on 2025-01-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_dt_income_debit_rename_ct_spending_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Initial balance'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='w_bank',
            field=models.CharField(blank=True, max_length=25, verbose_name='Bank name'),
        ),
    ]
