# Generated by Django 5.1.4 on 2025-01-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_wallet_initial_balance_alter_wallet_w_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='f_name',
            field=models.CharField(blank=True, max_length=24, verbose_name='Full wallet name'),
        ),
    ]
