# Generated by Django 5.1.4 on 2025-01-21 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_income_income_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.income_type', verbose_name='Income Type'),
        ),
    ]
