# Generated by Django 5.1.4 on 2025-01-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_income_income_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('name', models.CharField(db_index=True, max_length=5, verbose_name='Currency')),
                ('buy', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Buy')),
                ('sell', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sell')),
                ('source', models.URLField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'rate',
                'verbose_name_plural': 'rates',
                'ordering': ['date'],
            },
        ),
    ]
