# Generated by Django 5.1.4 on 2025-01-14 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_wallet_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.wallet', verbose_name='Wallet'),
        ),
    ]
