# Generated by Django 5.1.4 on 2025-01-16 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_income_comment_alter_spending_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Debit'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.income_type', verbose_name='Income Type'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Initial balance'),
        ),
    ]
