# Generated by Django 5.1.4 on 2025-01-16 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_income_income_type_alter_income_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.wallet', verbose_name='Wallet'),
        ),
    ]
